import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./assets/scss/style.scss";
import { ThemeProvider } from "./shared/components/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";
import MenuItem from "./shared/components/MenuItem";
import LayoutCustom from "./shared/components/LayoutCustom";

// const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
       
        <LayoutCustom>
          {children}
        </LayoutCustom>
      </body>
    </html>
  );
}
